version: "3"

services:
  redis:
    image: redis:latest
    networks: 
    - local
    ports:
    - "6379:6379"

  admin:
    image: rediscommander/redis-commander
    networks: 
    - local
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks: 
    - local

networks:
  local:
    driver: bridge   